### ISSUE TITLE
Update monolog/monolog to ^3.0

### ISSUE THREAD

**Issue by SmetDenis** [hamidrezaniazi/pecs#1]
**Is your feature request related to a problem? Please describe.**
This request is related to a compatibility problem in our project. We're currently using version 3.4 of the monolog/monolog library in our extensive project, which is an integral part of our CI/CD pipeline.

**Describe the solution you'd like**
The solution we seek is the upgrade of your PHP dependencies to accommodate monolog/monolog ^3.0. This update would ensure the compatibility of our project with the latest version of monolog and enable us to take advantage of all the features and benefits provided by this newer version.

**Describe alternatives you've considered**
We've considered sticking with the current version of our PHP dependencies and making use of workarounds or patches. However, this is not a viable long-term solution and could potentially introduce other issues and technical debt. Additionally, we've evaluated other logging libraries as potential replacements for monolog, but given that our project is deeply integrated with monolog, changing to a new library would require a significant refactoring effort and risk introducing new problems.

**Additional context**
We appreciate your attention to this matter and look forward to the upgrade. :)

**Comment by hamidrezaniazi** [comment]
Dear Denis,

Thank you for raising this compatibility issue. I'm glad to inform you that it has been addressed in the [latest release](https://github.com/hamidrezaniazi/pecs/releases/tag/1.0.0). This update includes support for Monolog 3.*.

Your feedback is valuable and helps improve the project.

Best regards,
Hamid
@hamidrezaniazi

**Comment by SmetDenis** [comment]
Thank you so much! :)
